services:
  web-dev:
    image: node:20-alpine
    container_name: webstorm-dev
    working_dir: /app

    volumes:
      - .:/app
      - dev-node-modules:/app/node_modules

    command: sh -c "npm install && npm run dev"

    ports:
      - "8080:80"
  jenkins:
#    image: jenkins/jenkins:lts
    container_name: jenkins-proj-ntwo
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:z
  verdaccio:
    image: verdaccio/verdaccio
    container_name: verdaccio-proj-ntwo
    ports:
      - "4873:4873"
    volumes:
      - verdaccio-storage:/verdaccio/storage
    environment:
      - VERDACCIO_LISTEN=0.0.0.0:4873
volumes:
  jenkins_home:
  dev-node-modules:
  verdaccio-storage: